{
 "title": "SmartSpaceDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Times feedback was bad",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gradio_feedback_total{Prediction_quality=\"Bad\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Times feedback was good",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gradio_feedback_total{Prediction_quality=\"Good\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "request_processing_seconds_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions Made",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gradio_predictions_total", "legendFormat": "__auto" }
   ]
  }
 ]
}