version: '3.8'

services:
  gradio-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "7860:7860"  # Gradio app
      - "8000:8000"  # Prometheus metrics from app
    container_name: gradio-app

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: prometheus
    depends_on:
      - gradio-app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - prometheus
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - /c/Users/deana/Downloads/SmartSpaceGit/SmartSpace-AI-powered-wall-decoration-placement/testingstructure/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - /c/Users/deana/Downloads/SmartSpaceGit/SmartSpace-AI-powered-wall-decoration-placement/testingstructure/monitoring/grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana-storage:

